" This file should be placed in the home directory as .vimrc
set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
" alternatively, pass a path where Vundle should install plugins
"call vundle#begin('~/some/path/here')

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'

filetype plugin indent on

Plugin 'christoomey/vim-tmux-navigator'

execute pathogen#infect()

" Search setup:
set incsearch
set ignorecase
set smartcase
"set hlsearch!
"nnoremap <F3> :set hlsearch!<CR>

set scrolloff=5

set tabstop=4
set autoindent
set copyindent
set shiftwidth=4
set smarttab
set expandtab

set nobackup
set nowritebackup

autocmd FileType javascript setlocal shiftwidth=2 tabstop=2
autocmd FileType html setlocal shiftwidth=2 tabstop=2
autocmd FileType css setlocal shiftwidth=2 tabstop=2

colorscheme jellybeans-dan
